#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/clear-street/clear-street-go,github.com/clear-street-internal/clear-street-active-go-staging"

echo "==> Running Go build"
go build ./...
